# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
#relative_permalinks: true

# Setup
timezone:            Africa/Nairobi
locale:              en_us
name:				 Chaos Theory
title:               Chaos Theory
tagline:             'You know nothing Chaos'
description:         'Discovery starts with accepting the obvious, that you know Nothing'
url:                 http://sasagichuki.github.io
rss:                 # rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/icon.png
disqus:              chaosnairobi

author:
  name:           	 Chaos Gichuki
  url:            	 http://chaos.co.ke
  # facebook:          username
  twitter:           kibee
  # google_plus:       username
  linkedin:          charlesgichuki
  dribbble:          kibee
  # pinterest:         username
  # kiva:              username

# fb_admins:           your facebook profile id
# fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
